local strutil = require( 'acid.strutil' )

local _M = {}

_M.types = {
    ['ps']      = 'application/postscript',
    ['ai']      = 'application/postscript',
    ['js']      = 'application/x-javascript',
    ['pl']      = 'application/x-perl',
    ['pm']      = 'application/x-perl',
    ['tk']      = 'application/x-tcl',
    ['ra']      = 'audio/x-realaudio',
    ['jar']     = 'application/java-archive',
    ['war']     = 'application/java-archive',
    ['ear']     = 'application/java-archive',
    ['hqx']     = 'application/mac-binhex40',
    ['doc']     = 'application/msword',
    ['pdf']     = 'application/pdf',
    ['eps']     = 'application/postscript',
    ['rss']     = 'application/rss+xml',
    ['rtf']     = 'application/rtf',
    ['kml']     = 'application/vnd.google-earth.kml+xml',
    ['kmz']     = 'application/vnd.google-earth.kmz',
    ['xls']     = 'application/vnd.ms-excel',
    ['ppt']     = 'application/vnd.ms-powerpoint',
    ['cco']     = 'application/x-cocoa',
    ['run']     = 'application/x-makeself',
    ['pdb']     = 'application/x-perl',
    ['prc']     = 'application/x-pilot',
    ['rar']     = 'application/x-rar-compressed',
    ['rpm']     = 'application/x-redhat-package-manager',
    ['sea']     = 'application/x-sea',
    ['swf']     = 'application/x-shockwave-flash',
    ['sit']     = 'application/x-stuffit',
    ['tcl']     = 'application/x-tcl',
    ['der']     = 'application/x-x509-ca-cert',
    ['pem']     = 'application/x-x509-ca-cert',
    ['crt']     = 'application/x-x509-ca-cert',
    ['xpi']     = 'application/x-xpinstall',
    ['zip']     = 'application/zip',
    ['mid']     = 'audio/midi',
    ['kar']     = 'audio/midi',
    ['mp3']     = 'audio/mpeg',
    ['gif']     = 'image/gif',
    ['jpg']     = 'image/jpeg',
    ['png']     = 'image/png',
    ['svg']     = 'image/svg+xml',
    ['tif']     = 'image/tiff',
    ['ico']     = 'image/x-icon',
    ['jng']     = 'image/x-jng',
    ['bmp']     = 'image/x-ms-bmp',
    ['css']     = 'text/css',
    ['htm']     = 'text/html',
    ['mml']     = 'text/mathml',
    ['txt']     = 'text/plain',
    ['jad']     = 'text/vnd.sun.j2me.app-descriptor',
    ['wml']     = 'text/vnd.wap.wml',
    ['htc']     = 'text/x-component',
    ['xml']     = 'text/xml',
    ['3gp']     = 'video/3gpp',
    ['mpg']     = 'video/mpeg',
    ['mov']     = 'video/quicktime',
    ['flv']     = 'video/x-flv',
    ['mng']     = 'video/x-mng',
    ['asx']     = 'video/x-ms-asf',
    ['asf']     = 'video/x-ms-asf',
    ['wmv']     = 'video/x-ms-wmv',
    ['avi']     = 'video/x-msvideo',
    ['atom']    = 'application/atom+xml',
    ['wmlc']    = 'application/vnd.wap.wmlc',
    ['jnlp']    = 'application/x-java-jnlp-file',
    ['midi']    = 'audio/midi',
    ['jpeg']    = 'image/jpeg',
    ['tiff']    = 'image/tiff',
    ['wbmp']    = 'image/vnd.wap.wbmp',
    ['html']    = 'text/html',
    ['3gpp']    = 'video/3gpp',
    ['mpeg']    = 'video/mpeg',
    ['xhtml']   = 'application/vnd.wap.xhtml+xml',
    ['shtml']   = 'text/html',
    ['jardiff'] = 'application/x-java-archive-diff',
}

function _M.by_fn(fn)
    local suffix = strutil.split(fn, '[.]')
    suffix = suffix[#suffix]

    return _M.types[suffix] or 'application/octet-stream'
end

return _M
